services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - app_bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    environment:
      - AWS_COGNITO_APP_CLIENT_ID=${AWS_COGNITO_APP_CLIENT_ID}
      - AWS_COGNITO_APP_CLIENT_SECRET=${AWS_COGNITO_APP_CLIENT_SECRET}
      - AWS_COGNITO_USER_POOL_ID=${AWS_COGNITO_USER_POOL_ID}
      - AWS_COGNITO_REGION=${AWS_COGNITO_REGION}
      - AWS_COGNITO_DOMAIN=${AWS_COGNITO_DOMAIN}
    tty: true
volumes:
  app_bundle:
